language: node_js
node_js:
  - "8"
  - "9"
services: mongodb  
cache:  
  directories:
    - "node_modules"
sudo: false
install:
  - npm install
deploy:
  provider: script
  skip_cleanup: true
  script: /bin/sh deploy.sh
  on:
    branch: master
script:
  - npm test
